name: Publish
on:
  push:
    branches:
    - main

  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: main
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
